### ISSUE TITLE
As an Admin, I want to be able to create a new product so that we can sell them to customers.

### ISSUE THREAD

**Issue by zikky17** [KYH-Net23/ProductProvider#1]
# Acceptance Criteria

- [x] There must be a create button that brings the admin to a form to create a new product.
- [x] There must be a form for the admin to fill out “Product Name”, “Product Price”, “Product Description”, and “Product Image”.
- [x] The form must be validated to guarantee correct information is written.
- [x] If the information is validated, the information is saved to a database, and the admin is returned to the products page, with the updated list.
- [x] The admin should see an error message if the product fails to be saved, and a success message if it succeeded.
- [x] If the form is invalid, the admin only needs to change the incorrect input field.

---

# Activity Diagram
![Image](https://github.com/user-attachments/assets/98ee1f6c-0269-4a98-ad03-d847d1d7332a)

---

# Sequence Diagram
![Image](https://github.com/user-attachments/assets/3fd2b274-6973-4d18-8b11-f0c0911478de)

---

# Tasks
- [x] #122
    - [x] Create a DB using an EF core. 

- [x] #123
    - [x] Create a product model that represents the input fields that are required. (ProductId(GUID), Product Name, Price, Image, Category, Description)
    - [x] Price should be non-negative

- [x] KYH-Net23/ProductsRepo#47
    - [x] Create a product model that represents the input fields that are required. (Product Name, Description, Price, Image, etc).

- [x] KYH-Net23/ProductsRepo#49
    - [x] Create a ProductService class with an interface(IProductService).
    - [x] Create a ProductRepository class with an interface (IProductRepository).
    - [x] Create a ProductFactory class.
    - [x] Create ProductContext that implements DbContext

- [x] KYH-Net23/ProductsRepo#54
    - [x] CreateNewProduct(Input formInput)

- [x] KYH-Net23/Rika#40
    - [x] Add a "Create New Product" button in the admin UI
    - [x] Add form when pressing the button, allowing admin to input in the fields.
    - [x] Return error/success messages, if the Create was successful or not.
    - [x] Add a red border on the incorrect input fields.

- [x] KYH-Net23/Rika#45
    - [x] Make sure the admin can't make any mistakes in the form.
    - [x] Display an error message on missing/wrong input.

- [x] KYH-Net23/ProductsRepo#64
    - [x] Make sure the ProductRepository has an established connection to the correct database.

- [x] KYH-Net23/ProductsRepo#66
    - [x] Write unit tests to ensure functionality is working correctly, write integration tests to ensure it cooperates with other systems.

---

# Test Case Descriptions

- [x] Test Case 1: Successfully Added a New Product

    Prerequisites:
    - Person is logged in as Admin.
    - Go to the admin dashboard.
    
    Steps:
    - Admin clicks the Add new product button.
    - Admin fills out the form correctly.
    - Press Save.
    
    Expected Result:
    - New product is created, and the list of products displays the newly created product with a success message.

- [x] Test Case 2: Failed to Add a New Product

    Prerequisites:
    - Person is logged in as Admin.
    - Go to the admin dashboard.
    
    Steps:
    - Admin clicks the Add new product button.
    - Admin fills out the form incorrectly.
    - Press Save.
    
    Expected Result:
    - An error message is displayed, indicating the issue with the input.

---
