### ISSUE TITLE
As an Admin, I want to be able to delete a product

### ISSUE THREAD

**Issue by Nant1ng** [KYH-Net23/ProductProvider#15]
# Acceptance Criteria

- [x] The product card must include a delete button.
- [ ] A confirmation dialog should appear, asking the admin to confirm or cancel the deletion.
- [ ] Only the admin should have access to the delete button.
- [ ] After a successful delete, the admin should see a confirmation message and be redirected to the products page.
- [ ] If the delete fails, an error message should appear, with an option to retry or return to the products page.

---

# Tasks

- [x] KYH-Net23/ProductsRepo#18
    - [x] Implement soft delete by adding a deleted flag or equivalent attribute in the product model.

- [x] KYH-Net23/ProductsRepo#19
    - [x] Add a DeleteProduct in ProductService class and interface IProductService to handle delete logic

- [x] KYH-Net23/Rika#27
    - [x] Add a delete button on the product card, that is only visible for the admins
    - [x] Show a conformations dialog to prevent accidents
    - [x] Display success message and redirect to the products page if the deletion was successful
    - [x] Show error message if deletion fails, with options to retry or return

- [x] KYH-Net23/ProductsRepo#26
    - [x] Write unit tests to ensure functionality is working correctly, write integration tests to ensure it cooperates with other systems.
    
---

# Test Case Descriptions

- [ ] Test Case 1: Successfully Delete a Product

    Prerequisites:
-     Person is logged in as Admin.

    Steps:
-     Admin navigates to the products page.
-     Admin clicks on the delete button on a product card.
-     A confirmation dialog appears, and the admin confirms deletion.
-     The product is removed from the database.

    Expected Result:
-     A success message appears, confirming the deletion.
-     Admin is redirected to the Products page, and the deleted product no longer appears.

- [ ] Test Case 2: Failed to Delete Product

    Prerequisites:
-     Person is logged in as Admin.

    Steps:
-     Admin navigates to the products page.
-     Admin clicks on the delete button on a product card.
-     A confirmation dialog appears, and the admin confirms deletion.
-     The delete operation fails due to a database error.
    
    Expected Result:
-     An error message is displayed.
-     Admin has an option to retry the deletion or refresh the page.

---
