### ISSUE TITLE
As an Admin, I want to be able to change the details  of an existing product so that the correct information is displayed.

### ISSUE THREAD

**Issue by Nant1ng** [KYH-Net23/ProductProvider#16]
# Acceptance Criteria

- [x] There must be an edit button that brings the admin to a form to edit the details of the existing product.
- [x] The edit button should be placed in an admin view for the products (each product has its own button).
- [x] The form must be validated to guarantee correct information is written.
- [x] If the information is validated, the information is saved to a database, and the admin is returned to the products page, with the updated list.
- [x] The admin should see an error message if the product fails to be saved, and a success message if it succeeded.
- [x] If the form is invalid, the admin only needs to change the incorrect input field.

---

# Activity Diagram
![Image](https://github.com/user-attachments/assets/4d779f8b-263c-464a-b603-36be59ef8dbf)

---

# Sequence Diagram
![Image](https://github.com/user-attachments/assets/6126b9fe-3ded-4c98-a5aa-ef8ab7f4692b)

---

# Tasks

- [x] KYH-Net23/Rika#32
    - [x] Create an Edit button for each product's details page.

- [x] KYH-Net23/ProductsRepo#31
    - [x] Create the Update method according to the sequence diagram.
- [x] #139

- [x] KYH-Net23/Rika#34
    - [x] Add an update product button in admin view.
    - [x] Ensure the form is pre-filled with the current information from the database when opened. 

- [x] KYH-Net23/Rika#37
    - [x] Make sure the admin can't make any mistakes in the form.
    - [x] Display an error message on missing / wrong input.

- [x] #154

- [x] KYH-Net23/ProductsRepo#39
    - [x] Write unit tests to ensure functionality is working correctly, write integration tests to ensure it cooperates with other systems.

---

# Test Case Descriptions

- [x] Test Case 1: Successfully Updated a Product

    Prerequisites:
-     Person is logged in as Admin.
-     Go to the admin dashboard.

    
    Steps:
-     Admin clicks the Edit button on one of the products.
-     Admin fills out the form correctly.
-     Press Save.

    
    Expected Result:
-     Current product is updated, the list of products displays the updated product, and a success message is shown.

- [x] Test Case 2: Failed to Update a Product

    Prerequisites:
-     Person is logged in as Admin.
-     Go to the admin dashboard.

    
    Steps:
-     Admin clicks the Edit button on one of the products.
-     Admin fills out the form incorrectly.
-     Press Save.

    
    Expected Result:
-     An error message is displayed, indicating the issue with the input.

---
