### ISSUE TITLE
As an Admin/Customer/Guest, I want to be able to view a list of all products.

### ISSUE THREAD

**Issue by Nant1ng** [KYH-Net23/ProductProvider#6]
# Acceptance Criterias 

- [x] A list of all products must be displayed on the products page.
- [x] Must display relevant information of the products on a product card.
- [x] If the list of products fails to load, an error message should be displayed and there should be an option to retry load products or refresh the page.

---
# Tasks

- [x] KYH-Net23/ProductsRepo#99
    - [x] Create a product model that represents the input fields that are required. (Product Name, Price, Image, etc).
  
- [x] KYH-Net23/ProductsRepo#100
    - [x] Create a ProductFactory class.
    - [x] Create ProductContext that implements DbContext.
    
- [x] KYH-Net23/ProductsRepo#101
    - [x] GetAllProducts() that fetch from the database.
    
- [x] KYH-Net23/Rika#184
    - [x] Design a product list page UI to display each product's name, price, image,etc (use the figma file for inspiration).
   
- [x] KYH-Net23/ProductsRepo#103
    - [x] Write xUnit tests to ensure viewModel factory functionality is working correctly.

---
# Test Case Descriptions

- [x] Test case 1: Successfully Map ProductEntity to ProductViewModel

    Prerequisites:
-     None

    Steps:
-     Create a ProductEntity with dummy data.
-     Send the ProductEntity into ProductViewModelFactory.GetProduct.
	
    Expected result:
-     productEntity.Id is the same as productViewModel.Id.
-     productEntity.Brand is the same as productViewModel.Brand.
-     productEntity.Model is the same as productViewModel.Model.
-     productEntity.Price is the same as productViewModel.Price.
-     productEntity.Image is the same as productViewModel.Image.

- [x] Test case 2: Successfully Map list of ProductEntities to list of ProductViewModels

    Prerequisites:
-     None

    Steps:
-     Create a list of ProductEntities with dummy data.
-     Send the ProductEntity lists into ProductViewModelFactory.GetProducts.
	
    Expected result:
-     ProductEntities[0] is the same as ProductViewModels[0]
-     ProductEntities[1] is the same as ProductViewModels[1]

---
